/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package battle_cioba;

import javax.swing.*;
import java.awt.*;
import java.text.NumberFormat;
import java.util.Locale;

/**
 * Dialog per visualizzare informazioni dettagliate su uno Stato.
 */
public class InfoStato extends javax.swing.JDialog {

    private Stato stato;
    
    /**
     * Creates new form InfoStato
     */
    public InfoStato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Costruttore che accetta uno Stato da visualizzare
     */
    public InfoStato(java.awt.Frame parent, boolean modal, Stato stato) {
        super(parent, modal);
        this.stato = stato;
        initComponents();
        
        // Centra il dialogo rispetto al parent
        setLocationRelativeTo(parent);
        
        // Imposta il titolo con il nome dello stato
        setTitle("Informazioni: " + stato.getNome());
        
        // Popola i componenti con i dati dello stato
        aggiornaInterfaccia();
    }
    
    /**
     * Popola l'interfaccia con i dati dello stato
     */
    private void aggiornaInterfaccia() {
        if (stato == null) return;
        
        // Formattazione numeri
        NumberFormat numberFormat = NumberFormat.getNumberInstance(Locale.ITALIAN);
        
        // Aggiorna le etichette con i dati dello stato
        lblNomeStato.setText(stato.getNome());
        
        // Gestione del presidente (che può essere un oggetto generico)
        String infoPresidente = "Non disponibile";
        if (stato.getPresidente() != null) {
            infoPresidente = stato.getPresidente().toString();
        }
        lblPresidente.setText(infoPresidente);
        
        // Popolazione
        lblPopolazione.setText(numberFormat.format(stato.getPopolazione()));
        
        // Potenza
        lblPotenza.setText(String.valueOf(stato.getPotenza()));
        
        // Capitale
        String infoCapitale = "Nessuna";
        if (stato.getCapitale() != null) {
            infoCapitale = stato.getCapitale().getNome();
        }
        lblCapitale.setText(infoCapitale);
        
        // Numero di regioni
        lblNumRegioni.setText(String.valueOf(stato.getRegioni().size()));
        
        // Opposizione
        lblOpposizione.setText(String.valueOf(stato.getOpposizione()));
        
        // Lista delle regioni
        StringBuilder regioni = new StringBuilder();
        for (Regione regione : stato.getRegioni()) {
            regioni.append("• ").append(regione.getNome()).append("\n");
        }
        txtAreaRegioni.setText(regioni.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Inizializza tutti i componenti dell'interfaccia
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Pannello superiore con informazioni principali
        JPanel infoPanel = new JPanel(new GridLayout(0, 2, 5, 5));
        
        // Nome dello stato (in grassetto)
        JLabel titleNomeStato = new JLabel("Nome Stato:");
        titleNomeStato.setFont(new Font(titleNomeStato.getFont().getName(), Font.BOLD, 14));
        lblNomeStato = new JLabel("");
        lblNomeStato.setFont(new Font(lblNomeStato.getFont().getName(), Font.BOLD, 14));
        
        infoPanel.add(titleNomeStato);
        infoPanel.add(lblNomeStato);
        
        // Presidente
        infoPanel.add(new JLabel("Presidente:"));
        lblPresidente = new JLabel("");
        infoPanel.add(lblPresidente);
        
        // Popolazione
        infoPanel.add(new JLabel("Popolazione:"));
        lblPopolazione = new JLabel("");
        infoPanel.add(lblPopolazione);
        
        // Potenza
        infoPanel.add(new JLabel("Potenza:"));
        lblPotenza = new JLabel("");
        infoPanel.add(lblPotenza);
        
        // Capitale
        infoPanel.add(new JLabel("Capitale:"));
        lblCapitale = new JLabel("");
        infoPanel.add(lblCapitale);
        
        // Numero regioni
        infoPanel.add(new JLabel("Numero regioni:"));
        lblNumRegioni = new JLabel("");
        infoPanel.add(lblNumRegioni);
        
        // Opposizione
        infoPanel.add(new JLabel("Opposizione:"));
        lblOpposizione = new JLabel("");
        infoPanel.add(lblOpposizione);
        
        // Pannello centrale con lista regioni
        JPanel regioniPanel = new JPanel(new BorderLayout(5, 5));
        regioniPanel.setBorder(BorderFactory.createTitledBorder("Regioni"));
        
        txtAreaRegioni = new JTextArea(10, 20);
        txtAreaRegioni.setEditable(false);
        txtAreaRegioni.setLineWrap(true);
        JScrollPane scrollPane = new JScrollPane(txtAreaRegioni);
        regioniPanel.add(scrollPane, BorderLayout.CENTER);
        
        // Pulsante chiudi in basso
        JButton btnChiudi = new JButton("Chiudi");
        btnChiudi.addActionListener(e -> dispose());
        
        // Aggiungi tutti i pannelli
        mainPanel.add(infoPanel, BorderLayout.NORTH);
        mainPanel.add(regioniPanel, BorderLayout.CENTER);
        mainPanel.add(btnChiudi, BorderLayout.SOUTH);
        
        getContentPane().add(mainPanel);
        pack();
        setSize(400, 500);
    }// </editor-fold>//GEN-END:initComponents

    // Dichiarazione dei componenti
    private JLabel lblNomeStato;
    private JLabel lblPresidente;
    private JLabel lblPopolazione;
    private JLabel lblPotenza;
    private JLabel lblCapitale;
    private JLabel lblNumRegioni;
    private JLabel lblOpposizione;
    private JTextArea txtAreaRegioni;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoStato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoStato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoStato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoStato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoStato dialog = new InfoStato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
